package com.incidentpb.service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

import org.springframework.context.annotation.Primary;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

import com.incidentpb.domain.IncidentSummary;

import lombok.extern.slf4j.Slf4j;

@Service
@Profile("mock")
@Primary
@Slf4j
/**
 * Disclaimer: This mock service is generated by AI
*/
public class MockGeminiAIService extends GeminiAIService {

    public MockGeminiAIService() {
        super();
    }

    @Override
    public IncidentSummary generateSummary(String title, String content) {
        return IncidentSummary.builder()
                .shortSummary("[MOCK] " + title)
                .rootCause("[MOCK] Root cause: " + truncate(content, 80))
                .impact("[MOCK] Impact: System degradation affecting users and services")
                .resolution("[MOCK] Resolution: Issue resolved by engineering team")
                .prevention("[MOCK] Prevention: Add monitoring, alerts, and testing")
                .build();
    }

    @Override
    public List<Float> generateEmbedding(String text) {
        List<Float> embedding = createSemanticEmbedding(text.toLowerCase());
        log.info("MOCK AI: Generated {} dimension embedding", embedding.size());
        return embedding;
    }
    
    private List<Float> createSemanticEmbedding(String text) {
        List<Float> embedding = new ArrayList<>(768);
        int seed = text.hashCode();
        Random rng = new Random(seed);
        for (int i = 0; i < 768; i++) {
            embedding.add(rng.nextFloat() * 0.1f - 0.05f);
        }
        Map<String, List<Integer>> semanticGroups = getSemanticGroups();
        for (Map.Entry<String, List<Integer>> entry : semanticGroups.entrySet()) {
            String keyword = entry.getKey();
            if (text.contains(keyword)) {
                for (Integer dim : entry.getValue()) {
                    if (dim < 768) {
                        embedding.set(dim, embedding.get(dim) + 0.5f);
                    }
                }
            }
        }
        return normalizeVector(embedding);
    }
    
    private Map<String, List<Integer>> getSemanticGroups() {
        Map<String, List<Integer>> groups = new HashMap<>();
        
        // Cache/Redis group (dimensions 0-50)
        List<String> cacheWords = Arrays.asList("redis", "cache", "memcache", "memory store");
        for (String word : cacheWords) {
            groups.put(word, createRange(0, 50));
        }
        
        // Database group (dimensions 51-100)
        List<String> dbWords = Arrays.asList("database", "postgres", "mysql", "sql", "query");
        for (String word : dbWords) {
            groups.put(word, createRange(51, 100));
        }
        
        // Performance group (dimensions 101-150)
        List<String> perfWords = Arrays.asList("slow", "timeout", "latency", "performance", "degradation");
        for (String word : perfWords) {
            groups.put(word, createRange(101, 150));
        }
        
        // Error group (dimensions 151-200)
        List<String> errorWords = Arrays.asList("error", "crash", "failure", "down", "outage");
        for (String word : errorWords) {
            groups.put(word, createRange(151, 200));
        }
        
        // Connection group (dimensions 201-250)
        List<String> connWords = Arrays.asList("connection", "pool", "socket", "network");
        for (String word : connWords) {
            groups.put(word, createRange(201, 250));
        }
        
        return groups;
    }
    
    private List<Integer> createRange(int start, int end) {
        List<Integer> range = new ArrayList<>();
        for (int i = start; i <= end; i++) {
            range.add(i);
        }
        return range;
    }
    
    private List<Float> normalizeVector(List<Float> vector) {
        double norm = 0.0;
        for (Float val : vector) {
            norm += val * val;
        }
        norm = Math.sqrt(norm);
        if (norm == 0.0) {
            return vector;
        }
        List<Float> normalized = new ArrayList<>();
        for (Float val : vector) {
            normalized.add((float) (val / norm));
        }
        return normalized;
    }
    
    private String truncate(String str, int length) {
        if (str == null || str.length() <= length) return str;
        return str.substring(0, length) + "...";
    }
}